# VabHub Frontend 版本配置文件

version: "1.0.0"

# 依赖关系配置
dependencies:
  - repo: "vabhub-core"
    version: ">=1.0.0"

# 变更日志配置
changelog:
  format: "keepachangelog"
  categories:
    - "Added"
    - "Changed"
    - "Fixed" 
    - "Removed"
    - "Security"

# 发布配置
release:
  # 预发布标签
  prerelease_tags:
    - "alpha"
    - "beta"
    - "rc"
  
  # 版本分支策略
  branches:
    main: "稳定版本"
    develop: "开发版本"
    release: "发布准备"
    hotfix: "紧急修复"

# 包管理器配置
package_managers:
  npm:
    name: "@vabhub/frontend"
    description: "VabHub Frontend - Modern Web Interface"
    keywords:
      - "vue"
      - "typescript"
      - "frontend"
      - "media-management"

# 构建配置
build:
  # Node.js 版本要求
  node_requires: ">=16.0.0"
  
  # 构建工具
  tools:
    - "vite"
    - "vue-tsc"
    - "eslint"
    - "prettier"
  
  # 构建脚本
  scripts:
    dev: "vite"
    build: "vue-tsc && vite build"
    preview: "vite preview"
    lint: "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix"

# 测试配置
test:
  # 测试框架
  framework: "vitest"
  
  # 测试覆盖要求
  coverage:
    minimum: 80
    
  # 浏览器兼容性
  browsers:
    - "chrome"
    - "firefox"
    - "safari"
    - "edge"

# 部署配置
deployment:
  # 静态文件服务器
  static_server: true
  
  # 端口配置
  port: 80
  
  # 环境变量
  environment:
    required:
      - "VITE_API_BASE_URL"
    
    optional:
      - "VITE_DEBUG"
      - "VITE_LOG_LEVEL"

# 最后更新
last_updated: "2025-10-26"